### ISSUE TITLE
Migrate to CPack for releasing code, rather than manually building packages.

### ISSUE THREAD

**Issue by keith923** [Electrostatics/apbs-pdb2pqr#417]
# Overview
## CMake INSTALL
The work to be done here has multiple parts, as it's a rather complex subject to be automating.  The way it works is that there are *install* directives in the CMake scripts that determine where to put files during a 'make install'.  An optional *PREFIX* is prepended to the locations specified with the *install* directives, and the files are copied to the resultant location during 'make install'.

## CPack
CPack goes one step further and allows us to specify an installation medium (tarball, OS X bundle, Windows installer, Linux package, etc.) into which the files are packaged up.  The structure of the packaging depends on the *install* directives mentioned above.

# TODO
## Structure
First, there is the issue of determining the release's structure.  The default that is currently defined in our CMake specification may or may not be what we really want.  On the surface it appears sensible for a linux distribution, but how it would translate to Windows or OS X is questionable.

### Current unix-y directory layout
.Below is what is currently built, slightly elided to concisely point out the main features
```
|-- bin
|-- include
|   `-- apbs
|       |-- fem
|       ...
|       `-- pmgc
|-- lib
`-- share
    `-- apbs
        |-- doc
        |-- examples
        |   |-- FKBP
        |   ...
        |   `-- solv
        |       `-- UHBD
        |-- tests
        `-- tools
            |-- bin
            |-- conversion
            |   `-- param
            |       |-- pdb2pqr
            |       `-- vparam
            |-- github
            |-- manip
            |-- matlab
            |   |-- MAPBS
            |   ...
            |-- mesh
            |-- osx
            |   `-- APBS.iconset
            |-- python
            |   `-- vgrid
            |-- visualization
            |   `-- opendx
            `-- windows
                |-- NSI configuration
               ...
```
As you can see, we include everything -- including the kitchen sink.  I don't particularly like this.  Perhaps it makes sense for linux to include the includes, but a lot of the stuff in tools (like OS X, and windows, not to mention that we ship the source code for tools/mesh (and probably more)) just doesn't belong.  I don't even know why we would include the includes quite frankly.  Unless there is a use case where users build something from our source that I'm not aware of.

In any case, I want to trim the fat on our release.  I don't want to ship a lot of the cruft that we are shipping.  I also think that it's most appropriate to have different output organization for different platforms.

It makes sense to put examples, and whatnot under /share/apbs for linux, but not at all for Windows, and probably not in as OS X bundle.  However, for a Homebrew install on OS X, it again makes sense.

### Linux
* tarball archive -- we have always, and will always want to provide one
* RPM?
* DEB?
### OS X
* tarball archive?
* Bundle -- this is the thing that every Mac user expects, and knows how to use
* Homebrew?  -- I personally like this option the best, and think that it's the most natural solution to distribute a gaggle of command line tools.  It's not something that CPack will help us with though.  It's also not difficult to make happen though.
### Windows
* NSIS installer

# Plan Forward
- [ ] Determine the set of release package formats that we will provide
- [ ] Determine optimal structure (directory/file) used by each package format
- [ ] Execute our decisions in the CMake/CPack build scripts, and/or any other necessary build tools

**Comment by keith923** [comment]
I'll chat with Juan about this.  Most likely it won't happen.

**Comment by keith923** [comment]
While I love this idea, I don't think that it's worth the investment, given that this is hopefully the last release of the legacy code base.
