### ISSUE TITLE
Create separate apbs repo

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#626]
* [x] Transfer code to the new repo (see below)
* [x] Transfer relevant issues to the new repo
* [x] Transfer relevant branches to the new repo
* [x] Transfer relevant tags and releases to the new repo
* [x] Remove APBS code (with `git delete` not `git filter-branch`) from this repo -- moved to https://github.com/Electrostatics/apbs-pdb2pqr/issues/628
* [x] Make sure the same people have access to the new repo
* [x] Make PyPI code for new repo -- moved to https://github.com/Electrostatics/apbs/issues/38
* [x] Update README.md for this repo -- moved to https://github.com/Electrostatics/apbs/issues/36
* [x] Update docs for new repo and http://www.poissonboltzmann.org/ -- moved to https://github.com/Electrostatics/apbs/issues/37

How to move the code:
```
mkdir split && cd split/
git clone https://github.com/Electrostatics/apbs-pdb2pqr.git
cd apbs-pdb2pqr/
git filter-branch --prune-empty --subdirectory-filter pdb2pqr/ master
git remote add origin https://github.com/Electrostatics/pdb2pqr.git
git remote set-url origin https://github.com/Electrostatics/pdb2pqr.git
git push -u origin master
```
